@startuml start
!includeurl https://raw.github.com/anoff/smartcards/master/assets/style.iuml

actor Host as p0
actor "Player #1" as p1
actor "Player #2" as p2


usecase "start game" as start
usecase "join game" as join

p0 --> start
p0 <.. start: session ID

p0 ..> p1: session ID
p0 ..> p2: session ID

p0 --> join
p1 --> join
p2 --> join

actor quizmaster
actor "Player #1" as p1a
actor "Player #2" as p2a

usecase "publish question" as qs
usecase "post answer" as a
usecase "vote on answers" as v

quizmaster --> qs
p1a --> a
p2a --> a

quizmaster --> v
p1a --> v
p2a --> v
@enduml